name: ci
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        std: [17, 20]
        sanitize: ["", "address,undefined", "thread"]
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFLX_CXX_STANDARD=${{ matrix.std }} -DFLX_SANITIZE="${{ matrix.sanitize }}"
      - name: Build
        run: cmake --build build -j
      - name: Test
        run: ctest --test-dir build --output-on-failure
